AWSTemplateFormatVersion: 2010-09-09
Description: > 
    Aminu / Nanodegree
    This Template deploys a VPC
Resources:
    VPC:
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: 10.0.0.0/16
            EnableDnsHostnames: true
#aws cloudformation create-stack  --stack-name myFirstTest --region us-east-1 --template-body file://testcfn.yml
