AWSTemplateFormatVersion: 2010-09-09
Description: > 
    Aminu / Nanodegree
    This Template deploys a VPC
Resources:
    VPC:
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: 10.0.0.0/16
            EnableDnsHostnames: true
# Run the aws command
#aws cloudformation create-stack  --stack-name myFirstTest --region us-east-1 --template-body file://testcfn.yml

# Alternate method - Shell script
# where $1, $2, and $3 can be replaced with the actual values passed as command-line arguments. 
# Note the --parameters and --capabilities options that we will learn in the upcoming lesson.

# aws cloudformation create-stack --stack-name $1 --template-body file://$2  --parameters file://$3 --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM" --region=us-west-2
# Alternate method - Batch Script You can also try a batch script (.bat) with a similar syntax, except that the actual values can be written as %1 instead as$1.

# Describe stack
# aws cloudformation describe-stacks --stack-name myFirstTest
